# Generated by Django 5.2 on 2025-04-15 14:49

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Packagecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packcatname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portfoliocategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portcatname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('confirmpassword', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('Identy_Card', models.ImageField(default='', upload_to='photos')),
                ('Role', models.CharField(default='designer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designer_Name', models.CharField(max_length=20)),
                ('package_design_style', models.CharField(max_length=10)),
                ('package_category', models.CharField(max_length=10)),
                ('BhkType', models.CharField(max_length=10, null=True)),
                ('package_price', models.FloatField()),
                ('time_duration', models.CharField(max_length=10)),
                ('package_desc', models.TextField()),
                ('package_img', models.ImageField(upload_to='photos')),
                ('ExtraServices', multiselectfield.db.fields.MultiSelectField(choices=[('Color Combination', 'Color Combination'), ('WallPaper', 'Wall Paper'), ('POP Design', 'POP Design'), ('Wardrobe Furniture', 'Wardrobe Furniture'), ('Lighting Design', 'Lighting Design'), ('Space Planning', 'Space Planning')], max_length=200)),
                ('package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packagecategory')),
                ('Designerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_packages', to='myapp.registermodel')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_packages', to='myapp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=20)),
                ('design_style', models.CharField(max_length=10)),
                ('package_type', models.CharField(max_length=10)),
                ('package_category', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(null=True)),
                ('totalamount', models.FloatField(null=True)),
                ('date_time', models.DateTimeField()),
                ('location', models.TextField()),
                ('BHKType', models.CharField(max_length=10)),
                ('propertySize', models.FloatField()),
                ('Time_duration', models.CharField(max_length=10)),
                ('requirement', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('Color Combination', 'Color Combination'), ('WallPaper', 'Wall Paper'), ('POP Design', 'POP Design'), ('Wardrobe Furniture', 'Wardrobe Furniture'), ('Lighting Design', 'Lighting Design'), ('Space Planning', 'Space Planning')], max_length=200)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages')),
                ('Designerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_bookings', to='myapp.registermodel')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_bookings', to='myapp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designer_Name', models.CharField(max_length=255, null=True)),
                ('aboutyourself', models.CharField(max_length=40)),
                ('designerskill', models.TextField(max_length=20)),
                ('experience', models.CharField(max_length=50)),
                ('sampleimage', models.ImageField(upload_to='photos')),
                ('catid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('designstyle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.portfoliocategory')),
                ('Designerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_portfolios', to='myapp.registermodel')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_portfolios', to='myapp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('phone_number', models.BigIntegerField()),
                ('message', models.TextField()),
                ('Designerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_contacts', to='myapp.registermodel')),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_contacts', to='myapp.registermodel')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('star', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review', models.TextField()),
                ('client_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.registermodel')),
            ],
        ),
    ]
